name: Apple Window Buttons CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: cmake g++ qtbase5-dev qtdeclarative5-dev libqt5qml5 libkf5plasma-dev libkf5plasmaquick5 libkdecorations2-dev libkf5coreaddons-dev libkf5declarative-dev

    - name: Build
      run: ./build.sh

